package com.smiletic.JavaHospital.SwingGUI;


import com.smiletic.JavaHospital.Assist.DataProvider;
import com.smiletic.JavaHospital.DAO.ContactdetailsEntity;
import com.smiletic.JavaHospital.DAO.PersonEntity;
import com.smiletic.JavaHospital.DAO.SexEntity;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.jdatepicker.JDatePicker;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;

public class MiniForm {
    private JTextField tfName;
    private JLabel lblName;
    private JComboBox cboSex;
    private JLabel lblSex;
    private JLabel lblDatePicker;
    private JLabel lblBriefStatement;
    private JTextField tfPhone1;
    private JTextField tfPhone2;
    private JLabel lblPhone1;
    private JLabel lblPhone2;
    private JTextField txtNextOfKInName;
    private JTextField txtRelationship;
    private JLabel lblNextOfKinName;
    private JLabel lblRtO;
    private JButton btnSubmit;
    private JPanel panelmain;
    private JDatePicker dpDateofBirth;
    private JTextArea txtaBriefStatement;

    public MiniForm() {
        List<SexEntity> sexes = DataProvider.getListofAllEntities(SexEntity.class);
        for (SexEntity sex : sexes
        ) {
            cboSex.addItem(sex);
        }

        btnSubmit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DataProvider.insertMiniform(tfName.getText(), (SexEntity) cboSex.getSelectedItem(), txtaBriefStatement.getText(),
                        Integer.toString(dpDateofBirth.getModel().getYear()), Integer.toString(dpDateofBirth.getModel().getMonth()), Integer.toString(dpDateofBirth.getModel().getDay()),
                        tfPhone1.getText(), tfPhone2.getText(), txtNextOfKInName.getText(), txtRelationship.getText());
            }
        });
    }


    public static void main(final String[] args) throws Exception {
        JFrame frame = new JFrame("MiniForm");
        frame.setContentPane(new MiniForm().panelmain);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);


    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelmain = new JPanel();
        panelmain.setLayout(new GridBagLayout());
        tfName = new JTextField();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelmain.add(tfName, gbc);
        lblName = new JLabel();
        lblName.setText("Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelmain.add(lblName, gbc);
        cboSex = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelmain.add(cboSex, gbc);
        lblSex = new JLabel();
        lblSex.setText("Sex");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelmain.add(lblSex, gbc);
        lblDatePicker = new JLabel();
        lblDatePicker.setText("D/O/B");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelmain.add(lblDatePicker, gbc);
        dpDateofBirth = new JDatePicker();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panelmain.add(dpDateofBirth, gbc);
        lblBriefStatement = new JLabel();
        lblBriefStatement.setText("BriefStatement");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelmain.add(lblBriefStatement, gbc);
        tfPhone1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelmain.add(tfPhone1, gbc);
        tfPhone2 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelmain.add(tfPhone2, gbc);
        lblPhone1 = new JLabel();
        lblPhone1.setText("Phone 1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelmain.add(lblPhone1, gbc);
        lblPhone2 = new JLabel();
        lblPhone2.setText("Phone 2");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelmain.add(lblPhone2, gbc);
        txtNextOfKInName = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelmain.add(txtNextOfKInName, gbc);
        txtRelationship = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelmain.add(txtRelationship, gbc);
        lblNextOfKinName = new JLabel();
        lblNextOfKinName.setText("Next of Kin Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelmain.add(lblNextOfKinName, gbc);
        lblRtO = new JLabel();
        lblRtO.setText("Relationship to pat");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelmain.add(lblRtO, gbc);
        btnSubmit = new JButton();
        btnSubmit.setText("SUBMIT");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panelmain.add(btnSubmit, gbc);
        txtaBriefStatement = new JTextArea();
        txtaBriefStatement.setRows(6);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        panelmain.add(txtaBriefStatement, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelmain;
    }

}
